DROP TABLE IF EXISTS hospital;

CREATE TABLE IF NOT EXISTS hospital (
	code SERIAL PRIMARY KEY,
	state VARCHAR(5) NOT NULL,
	name VARCHAR(30) NOT NULL UNIQUE,
	tel VARCHAR(15),
	ext VARCHAR(7),
	contact VARCHAR(7),
	addr VARCHAR(50)
	);

SELECT * FROM hospital;